name: west_build_demo
run-name: ${{ github.actor }} is doing west build 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/zephyrproject-rtos/ci:v0.26.11
      options: '--entrypoint /bin/bash'
    steps:
      - name: Build
        run: |
          pwd
          mkdir -p /repo-cache/zephyrproject
          cd /repo-cache/zephyrproject
          git clone https://github.com/zephyrproject-rtos/zephyr.git
          west init -l zephyr
          west update
          cd zephyr
          pwd
          ls /opt/toolchains
          echo "ZEPHYR_SDK_INSTALL_DIR=/opt/toolchains/zephyr-sdk-$( cat SDK_VERSION )" >> $GITHUB_ENV
          west build -p always -b nrf52840dk/nrf52840 samples/basic/blinky
