name: west_build_demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: List files in the repository
        run: |
          ls -al ${{ github.workspace }}
      - name: get directory
        run: |
          df -h

      - name: Setup Zephyr project
        uses: zephyrproject-rtos/action-zephyr-setup@v1.0.2
        with:
          app-path: app
          toolchains: arm-zephyr-eabi
          sdk-version: 0.16.5-1

      - name: Build
        run: |
          west build app
