name: west_build_demo
run-name: ${{ github.actor }} is doing west build 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/zephyrproject-rtos/ci:v0.26.11
      options: '--entrypoint /bin/bash'
    steps:
      - name: Build
        run: |
          pwd
          echo ${ZSDK_VERSION}
          whoami
          ls /home/user/.cmake
          ls /root/.cmake
          ls /root/.cmake/packages
          mkdir -p /repo-cache/zephyrproject
          cd /repo-cache/zephyrproject
          git clone https://github.com/zephyrproject-rtos/zephyr.git
          west init -l zephyr
          west update
          cd zephyr
          echo "ZEPHYR_SDK_INSTALL_DIR=/opt/toolchains/zephyr-sdk-$( cat SDK_VERSION )" >> $GITHUB_ENV
          echo ${{ env.ZEPHYR_SDK_INSTALL_DIR }}
          echo "ZEPHYR_SDK_INSTALL_DIR=/opt/toolchains/zephyr-sdk-$( cat SDK_VERSION )"


      - name: get-Env
        run: echo "ZEPHYR_SDK_INSTALL_DIR -> ${ env.ZEPHYR_SDK_INSTALL_DIR } "


