name: west_build_demo
run-name: ${{ github.actor }} is doing west build 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/zephyrproject-rtos/ci:v0.26.11
      options: '--entrypoint /bin/bash'

    steps:
      - name: setup sdk
        run: |
          whoami
          /opt/toolchains/zephyr-sdk-0.16.5/setup.sh -c
      - name: Build
        run: |
          pwd
          echo ${ZSDK_VERSION}
          whoami
          ls /home/user/.cmake
          ls /root/.cmake
          ls /root/.cmake/packages
          mkdir -p /repo-cache/zephyrproject
          cd /repo-cache/zephyrproject
          git clone https://github.com/zephyrproject-rtos/zephyr.git
          west init -l zephyr
          west update
          cd zephyr
          west build -p always -b nrf52840dk_nrf52840 samples/basic/blinky





