name: west_build_demo
run-name: ${{ github.actor }} is doing west build 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/zephyrproject-rtos/ci:v0.26.11
      options: '--entrypoint /bin/bash'
    steps:
      - name: Build
        working-directory: zephyr
        run: |
          pwd
          cmake --version
          python3 --version
          df -h

